spring.application.name=ORDER-SERVICE
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/orderdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Shally@183
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

resilience4j.circuitbreaker.instances.productService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.productService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.productService.sliding-window-size=10

# Register service with IP address
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=127.0.0.1